// smaller file

const cars = [
  {
    Name: "chevrolet chevelle concours (sw)",
    Miles_per_Gallon: null,
    Cylinders: 8,
    Displacement: 350,
    Horsepower: 165,
    Weight_in_lbs: 4142,
    Acceleration: 11.5,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "ford torino (sw)",
    Miles_per_Gallon: null,
    Cylinders: 8,
    Displacement: 351,
    Horsepower: 153,
    Weight_in_lbs: 4034,
    Acceleration: 11,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "plymouth satellite (sw)",
    Miles_per_Gallon: null,
    Cylinders: 8,
    Displacement: 383,
    Horsepower: 175,
    Weight_in_lbs: 4166,
    Acceleration: 10.5,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "amc rebel sst (sw)",
    Miles_per_Gallon: null,
    Cylinders: 8,
    Displacement: 360,
    Horsepower: 175,
    Weight_in_lbs: 3850,
    Acceleration: 11,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "dodge challenger se",
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 383,
    Horsepower: 170,
    Weight_in_lbs: 3563,
    Acceleration: 10,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "plymouth 'cuda 340",
    Miles_per_Gallon: 14,
    Cylinders: 8,
    Displacement: 340,
    Horsepower: 160,
    Weight_in_lbs: 3609,
    Acceleration: 8,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "ford mustang boss 302",
    Miles_per_Gallon: null,
    Cylinders: 8,
    Displacement: 302,
    Horsepower: 140,
    Weight_in_lbs: 3353,
    Acceleration: 8,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "chevrolet monte carlo",
    Miles_per_Gallon: 15,
    Cylinders: 8,
    Displacement: 400,
    Horsepower: 150,
    Weight_in_lbs: 3761,
    Acceleration: 9.5,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
    Name: "buick estate wagon (sw)",
    Miles_per_Gallon: 14,
    Cylinders: 8,
    Displacement: 455,
    Horsepower: 225,
    Weight_in_lbs: 3086,
    Acceleration: 10,
    Year: "1970-01-01",
    Origin: "USA",
  },
];    
